# Generated by Django 4.1.5 on 2023-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_grad_year_employee_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
    ]
